export enum MembershipFeatures {
    FREE_SHIPPING_ORDERS = 'FREE_SHIPPING_ORDERS',
    DISCOUNT_ON_ALL_ORDERS = 'DISCOUNT_ON_ALL_ORDERS',
    REWARD_POINTS_CASHBACK = 'REWARD_POINTS_CASHBACK',
    FREE_ONLINE_CONSULTATION = 'FREE_ONLINE_CONSULTATION',
    FREE_SECOND_OPINION_CONSULTATION = 'FREE_SECOND_OPINION_CONSULTATION',
    LAB_TEST_BOOKING = 'LAB_TEST_BOOKING',
}
